#   ______________  
#  |         .__. |  ___           _          _   ___                 _          
#  | ._-.    |  | | | _ \ ___  ___| |_  __ _ | | / __| ___  _ _ __ __(_) __  ___ 
#  |         '""' | |  _// _ \(_-<|  _|/ _` || | \__ \/ -_)| '_|\ V /| |/ _|/ -_)
#  |     -.,-_    | |_|  \___//__/ \__|\__,_||_| |___/\___||_|   \_/ |_|\__|\___|
#  |______________| 
#

####################
# General Settings #
####################

## PostalService requires a database to function. Currently MySQL is supported.
database:
    user: root
    password: 1234
    host: 127.0.0.1
    port: 3306
    database: someName

## Here you can enable or disable each type of mail
# PostalService has 4 mail types built-in:
#   Letters - Text only messages
#   Package - In-game Items
#   Payment - Money/Currency (requires Vault)
#   Xp      - XP points (not levels)
enabled-mail-types:
    letter: true
    package: true
    payment: true
    xp: true
     
## Toggle the use of UUIDs
# If disabled, PostalService will track player data using
# player names. If the server is running in offline mode,
# UUIDs will automatically be disabled. To force the use of
# UUIDS in offline mode, set this to "always". 
use-uuids: true

## Toggle on or off the update checker
# If the update checker finds an update, it will notify players with the
# postalservice.update permission when they login.
#
# You can also choose to have new versions auto downloaded as well.
# There are 3 auto download settings you can choose from:
#   - all: This will download all updates as they become available.
#   - bugfix: This will only download bugfix updates to your current version,
#             and you will have to manually update for feature upates.
#   - none: This will disable auto downloading for all updates.
update-checker:
    enabled: true
    auto-download: all

## Turning on debug mode may reveal errors that can be used to help 
# solve problems.
debug-mode: false


##################
# World Settings #
##################

## World groups allow you to segregate where mail items can be claimed. 
# This is useful if you have worlds with different inventories and you don't want
# players sending things across universes.
# For example, mail sent from a world in a "Survival Universe" would not be
# claimable from a world in a "PvP Universe".
# You can define as many groups as you like. Each group name must be 
# different from one another.

enable-world-groups: false

world-groups:
#    Survival Universe:
#      - survival_main
#      - survival_main_nether
#
#    Some Other Group:
#      - another_world

## Here you can set certain mail types to ignore world groups and 
# be claimable in all worlds.
# For example, say all your universes share the same economy. 
# In this case, you may want Payments to ignore world groups so players can 
# send money across universes but may want Packages to stay within world groups 
# so items can't be shared.
mail-types-that-ignore-world-groups:
#   - payment
  
## Worlds listed in this blacklist prevent players from running any PostalService 
# commands or opening mailboxes.
# This includes the ability to check mail, send mail, create mailboxes, etc.
world-blacklist:
  - worldname


#################
# User Settings #
#################

## This is the max inbox/sent size per permission group.
# If a permission group is undefined, the default is used.
# This feature requires Vault. If Vault is not present, the default is used
# for everyone.
box-sizes:
    default: 50
#    permission-group: 75


## Set this to true to make players be unable to receive mail if their inbox is full.
# If set to false, old mail will instead make way for new mail automatically. 
# Old mail is never deleted in this case, and will reappear if the player 
# deletes other mail to make room.
hard-enforce-inbox-limit: true


## Enable or disable when the unread mail notification is shown to players.
unread-mail-notifications:
    on-receive-mail: true
    on-login: true


####################
# Mailbox Settings #
####################

## Enable or disable the Mailbox feature
# Mailboxes are chests that players have registered as a Mailbox.
# Clicking on these chests will open up the Postal Service main menu
# GUI where players can view their inbox.
# If disabled, players can type /mail to access the main menu.
enable-mailboxes: true

## Enable this if you want to require players to be near a mailbox
# to send mail. Enabling this will also make opening mailboxes the only
# way to view the main menu GUI.
require-mailbox: true

## This is the max number of mailboxes per permission group.
# If a permission group is undefined, the default is used.
# This feature requires Vault. If Vault is not present, the default is used
# for everyone.
mailbox-limits:
    default: 5
#    permission-group: 10


#########################
# Trading Post Settings #
#########################
## UPCOMING FEATURE! THESE SETTINGS CURRENTLY DO NOTHING ##

enable-trading-post: false

require-same-mailbox: false

allow-cross-world-trades: false


#########################
# Localization Settings #
#########################

## Here you can change the pattern used to format the date and time for mail.
# Learn how to format patterns: http://goo.gl/n8qMk0
# Then test your pattern here: http://goo.gl/WCaX6i
date-format: "MMM d, yyyy h:mm a"

## This automatically translates month and day names in the date format
locale-tag: "en-US"

## Change the default time zone in which the time is displayed.
# Players can also change the timezone for themselves individually
# with the command: /mail timezone <zone>
time-zone: "UTC"

########################################
# Don't touch please
config-version: 1.0